language: node_js
node_js:
  - 4
  - 6
  - 7

os:
  - linux
  - osx

install:
  - npm -g install npm@3
  - npm install
  # install all resolver deps
  - "for resolver in ./resolvers/*; do cd $resolver && npm install && cd ../..; done"

script:
  - "npm test"
  - "for resolver in ./resolvers/*; do cd $resolver && npm test && cd ../..; done"

after_success:
  - npm run coveralls
