# Test against this version of Node.js
environment:
  matrix:
  - nodejs_version: "4"
  - nodejs_version: "6"

# platform:
#   - x86
#   - x64

# Install scripts. (runs after repo cloning)
install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version

  # update npm (only needed for Node 0.10)
  - npm -g install npm@3
  # - set PATH=%APPDATA%\npm;%PATH%

  # install modules
  - npm install

  # todo: learn how to do this for all .\resolvers\* on Windows
  - cd .\resolvers\webpack && npm install && cd ..\..
  - cd .\resolvers\node && npm install && cd ..\..

# Post-install test scripts.
test_script:

  # Output useful info for debugging.
  - node --version
  - npm --version

  # core tests
  - npm test

  # resolver tests
  - cd .\resolvers\webpack && npm test && cd ..\..
  - cd .\resolvers\node && npm test && cd ..\..

on_success:
  - npm run coveralls

# Don't actually build.
build: off
