name: 'Tests: packages'

on: [pull_request, push]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

permissions:
  contents: read

jobs:
  matrix:
    runs-on: ubuntu-latest
    outputs:
      latest: ${{ steps.set-matrix.outputs.requireds }}
      minors: ${{ steps.set-matrix.outputs.optionals }}
    steps:
      - uses: ljharb/actions/node/matrix@main
        id: set-matrix
        with:
          type: 'majors'
          preset: '>= 6' # preset: '>=4' # see https://github.com/import-js/eslint-plugin-import/issues/2053
          versionsAsRoot: true

  tests:
    needs: [matrix]
    name: 'packages'
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: ${{ fromJson(needs.matrix.outputs.latest) }}
        eslint:
          - 8
          - 7
        package:
          - resolvers/node
          - resolvers/webpack
          # - memo-parser
          # - utils

    steps:
      - uses: actions/checkout@v4
      - uses: ljharb/actions/node/install@main
        name: 'nvm install ${{ matrix.node-version }} && npm install'
        env:
          NPM_CONFIG_LEGACY_PEER_DEPS: ${{ matrix.node-version == 11 && false || true }}
          ESLINT_VERSION: ${{ matrix.eslint }}
          TRAVIS_NODE_VERSION: ${{ matrix.node-version }}
        with:
          node-version: ${{ matrix.node-version }}
          after_install: npm run copy-metafiles && ./tests/dep-time-travel.sh && cd ${{ matrix.package }} && npm install
          skip-ls-check: true
      - run: cd ${{ matrix.package }} && npm run tests-only
      - uses: codecov/codecov-action@v3.1.5

  packages:
    name: 'packages: all tests'
    needs: [tests]
    runs-on: ubuntu-latest
    steps:
      - run: 'echo tests completed'
